### ISSUE TITLE
Unable to mint.

### ISSUE THREAD

**Issue by lakai** [coinbase/nft-dapp-starter-kit#25]
Everything is great until you try to mint.  It just says Error  under the button in red.

**Comment by jeongmincho** [comment]
sadness! sorry to hear. can you elaborate a bit more on your setup? was this on your local build with a deployed contract? or on one of our sample sites? can you share what error was on the console?

**Comment by gmertk** [comment]
I think I ran into a similar issue. Some more info below in case it helps.

Minting from https://nonfungiblecoinbaes.vercel.app/mint with Coinbase Wallet v2.21.1 was failing in the following request:

```
curl 'https://eth-rinkeby.alchemyapi.io/v2' \
  -H 'authority: eth-rinkeby.alchemyapi.io' \
  -H 'accept: */*' \
  -H 'accept-language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'content-type: application/json' \
  -H 'origin: https://nonfungiblecoinbaes.vercel.app' \
  -H 'referer: https://nonfungiblecoinbaes.vercel.app/' \
  --data-raw '{"method":"eth_blockNumber","params":[],"jsonrpc":"2.0","id":5}' \
```

Response returned:
```
{"message":"Not Found","logref":null,"path":null,"_links":{"self":{"href":"/v2","templated":false,"profile":null,"deprecation":null,"title":null,"hreflang":null,"type":null,"name":null}},"_embedded":{"errors":[{"message":"Page Not Found","logref":null,"path":null,"_links":{},"_embedded":{}}]}}
```

The weird part was that the Rinkeby RPC settings was `https://rinkeby-infura.wallet.coinbase.com` (by default). 

Re-connecting the wallet fixed the issue as the eth_blockNumber request started to go to infura again.

**Comment by jeongmincho** [comment]
@lakai if you can share the error in your console when the client side show "Error" that would be helpful for me to debug the issue. thanks!

@gmertk thanks for the detailed info. did you configure your frontend with your own infura RPC URL? i believe `https://rinkeby-infura.wallet.coinbase.com` is the default endpoint that Coinbase Wallet uses on their side. in any case, i'm glad the issue was resolved. let me know if it happens again.
